// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxGIp_E4N1sX6rc3MpMMwQnabnlc1c3yw',
    appId: '1:508410907600:web:e81c25a2d3b3c1b06f87d5',
    messagingSenderId: '508410907600',
    projectId: 'project-b-c-vw85yk',
    authDomain: 'project-b-c-vw85yk.firebaseapp.com',
    storageBucket: 'project-b-c-vw85yk.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXWTnJOTZmLgs6p_UVWt3ad5tzowLuSXs',
    appId: '1:508410907600:android:9c6fbc3c85ae1b4a6f87d5',
    messagingSenderId: '508410907600',
    projectId: 'project-b-c-vw85yk',
    storageBucket: 'project-b-c-vw85yk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxII4t6Nwnkzw1UfmyQWBQgmHL7SNLWcY',
    appId: '1:508410907600:ios:8b64beec068bc2406f87d5',
    messagingSenderId: '508410907600',
    projectId: 'project-b-c-vw85yk',
    storageBucket: 'project-b-c-vw85yk.appspot.com',
    iosClientId: '508410907600-sf97ru8qk4f06uurko8vbqjmobdh3d75.apps.googleusercontent.com',
    iosBundleId: 'com.example.webadmincircular',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxII4t6Nwnkzw1UfmyQWBQgmHL7SNLWcY',
    appId: '1:508410907600:ios:acf329d5b7e46eb86f87d5',
    messagingSenderId: '508410907600',
    projectId: 'project-b-c-vw85yk',
    storageBucket: 'project-b-c-vw85yk.appspot.com',
    iosClientId: '508410907600-ctbfmvejh5sr7j2faerb61fnk3o53trr.apps.googleusercontent.com',
    iosBundleId: 'com.example.webadmincircular.RunnerTests',
  );
}
